---
title: "`dispatch_datain` function"
subtitle: "ADL-binder group"
---


```{r, echo=FALSE}
#--- Trace
Tinit <- "ADL-binder-dispatch_datain-"  # Matches file name
Tr  <- paste0(Tinit, 1)
```


<!--- ===== (ADL) binder FCMP group ==== --->


<!--- (ADL) binder::dispatch_datain function --->

## `dispatch_datain` function

_Purpose:_ Returns the name of input SAS dataset for a given year  

 _Arguments:_  

* `studyr`: Study year 

_Syntax:_ 

``` 
  data_name = dispatch_datain(1992);
```


_Example:_

```{r, echo=FALSE}
#--- Trace
Tr  <- paste0(Tinit, 51)
```


```{r ADL-binder-dispatch_datain, eval=FALSE}
/*--- ADL-binder-dispatch_datain --- */
data yearx;
   year = 1992; output;
   year = 1995; output;
   year = 2002; output;
   year = 2010; output;
run;
 
data dt_name;
   set yearx;
   HRS_data = dispatch_datain(year);
run;
;
Title "dispatch_datain function executed";
proc print data = dt_name;
run;
``` 


Output: dispatch_datain function executed;

```{sas, ref.label="ADL-binder-dispatch_datain", engine.path=saspath}

```{r, echo=FALSE}
#--- Trace
Tr  <- paste0(Tinit, 99)
```




