---
title: "Use FCMP"
output:
  rmdformats::readthedown:
     lightbox: true
     use_bookdown: true
---

```{r sas-ininit, echo =FALSE}
 library(rmdformats)
 Tinit <- "main-why_grp-"
 # https://www.r-bloggers.com/2019/09/create-rmarkdown-document-with-sas-code-and-output-sas-engine/
 saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
 cdir <- getwd()
```

Current directory: `r cdir`

# LINKS

Links to Step files

* [Step1](../05-use-FCMP-prj/info-prj5/)
* FCMP info:   [_CMPLIB_INFO](../01-create-FCMP-prj/_cmplib_info/)
* SAS snippets: [SASEX](./sasx/) 

# List of FCMP functions/subroutines

* Variables with the info on FCMp library

```{r fcmp-contents, file ="./sasx/01_FCMP-contents.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-contents", echo=FALSE, engine.path = saspath}
```

* List of FCMP functions/subroutines groups


```{r fcmp-grp-list, file ="./sasx/01_FCMP-grp_list.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-grp-list", echo=FALSE, engine.path = saspath}
```


* List of FCMP functions/subroutines (organized by FCMP groups)


```{r fcmp-fun-list, file ="./sasx/01_FCMP-fun_list.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-fun-list", echo=FALSE, engine.path = saspath}
```

