---
title: "FCMP cmlib"
---

```{r sas-ininit, echo =FALSE}
 library(rmdformats)
 Tinit <- "main-why_grp-"
 # https://www.r-bloggers.com/2019/09/create-rmarkdown-document-with-sas-code-and-output-sas-engine/
 saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
 cdir <- getwd()
```

Current directory: `r cdir`

# LINKS 

* FCMP source: [FCMP_SOURCE](./fcmp_source/)
* FCMP info:   [_CMPLIB_INFO](./_cmplib_info/)
* SAS examples: [SASEX](./sasex/) 

# List of FCMP functions/subroutines

* Variables with the info on FCMp library

```{r fcmp-contents, file ="./sasex/fcmp-contents.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-contents", echo=FALSE, engine.path = saspath}
```

* List of FCMP functions/subroutines groups


```{r fcmp-grp-list, file ="./sasex/fcmp-grp_list.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-grp-list", echo=FALSE, engine.path = saspath}
```


* List of FCMP functions/subroutines (organized by FCMP groups)


```{r fcmp-fun-list, file ="./sasex/fcmp-fun_list.sas", eval= FALSE, echo=FALSE}
```

```{sas , ref.label = "fcmp-fun-list", echo=FALSE, engine.path = saspath}
```

* Example template

```{r ex1-sas, file = "./sasex/example-template.sas", eval=FALSE, echo=FALSE}
```

```{sas , ref.label = "ex1-sas", engine.path = saspath}
```

